<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Sublime Text syntax definition for the TWiki/Foswiki markup language. Use AAAPackageDev to generate a Plist file from this.</string>
	<key>fileTypes</key>
	<array>
		<string>twiki</string>
		<string>foswiki</string>
	</array>
	<key>name</key>
	<string>TWiki/Foswiki</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#noautolink</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#top-no-wikiword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#wikiword-link</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>anchor</key>
		<dict>
			<key>match</key>
			<string>^#(?:[A-Z][a-z0-9]+){2,}[A-Za-z0-9]*</string>
			<key>name</key>
			<string>constant.other.anchor.twiki</string>
		</dict>
		<key>bold-text</key>
		<dict>
			<key>begin</key>
			<string>(?x)               (?&lt;=^|[\s\(!]) (\*) (?=(\S|\S.*?\S)  \*    ($|[\s,\.\?!:;\)]))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bold.begin.twiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?x) ((?=[^\*]*$)|(?&lt;=                                 \S) (\*) (?=$|[\s,\.\?!:;\)]))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bold.end.twiki</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.bold.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Don't match nested bold text.</string>
					<key>match</key>
					<string>\*</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>bulleted-list</key>
		<dict>
			<key>begin</key>
			<string>^(?:   )+(\*) </string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.bulleted-list.twiki</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Multiple of 3 spaces, asterisk, a space.</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.list.unnumbered.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>&lt;!--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.twiki</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Like a HTML comment, but may contain variable definitions.</string>
			<key>end</key>
			<string>--\s*&gt;</string>
			<key>name</key>
			<string>comment.block.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-definition</string>
				</dict>
			</array>
		</dict>
		<key>definition-list</key>
		<dict>
			<key>begin</key>
			<string>^(?:   )+(\$)(?=.*: )</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.definition-list.begin.twiki</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Multiple of 3 spaces, '$', arbitrary amount of text (which may be formatted), ':', at least one space. The last ': ' string on the line is matched.</string>
			<key>end</key>
			<string>(:) </string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.definition-list.end.twiki</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.other.definitionlist</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>forced-link</key>
		<dict>
			<key>begin</key>
			<string>(?x)  (?&lt;!!)  (\[\[)  (?= [^\]\[]* \]\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.link.begin.twiki</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A [[link]] link. Can be escaped with !, but not &lt;nop&gt;.</string>
			<key>contentName</key>
			<string>markup.underline.link.twiki</string>
			<key>end</key>
			<string>(\]\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.link.end.twiki</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.link.forced.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-reference</string>
				</dict>
			</array>
		</dict>
		<key>formatted-text</key>
		<dict>
			<key>comment</key>
			<string>Formatted text rules: 1) cannot span multiple lines, 2) must be preceeded by start of line, space or [(!], 3) must be followed by end of line space or 'normal punctuation': [,.?!:;)].</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bold-text</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic-text</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw-text</string>
				</dict>
			</array>
		</dict>
		<key>heading</key>
		<dict>
			<key>begin</key>
			<string>^(---+\+{1,6})</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.twiki</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Heading: 3 or more dashes, 1-6 plus signs, heading text. '!!' excludes name from TOC, or trims it.</string>
			<key>contentName</key>
			<string>entity.name.heading.twiki</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.heading.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(!!)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.heading.notoc.twiki</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>inet-link</key>
		<dict>
			<key>match</key>
			<string>(?x) (?&lt;!!) (https?|s?ftp|ftps|news|file|smb|afp|nfs|gopher|txmt):// [-:@a-zA-Z0-9_.,~%+/?=&amp;amp;#]+</string>
			<key>name</key>
			<string>markup.underline.link.inet.twiki</string>
		</dict>
		<key>inline</key>
		<dict>
			<key>comment</key>
			<string>Inlined (not at top-level) markup.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#wikiword-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-no-wikiword</string>
				</dict>
			</array>
		</dict>
		<key>inline-no-wikiword</key>
		<dict>
			<key>comment</key>
			<string>Inlined (not at top-level) markup (excluding wiki word links).</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#forced-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#labelled-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inet-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mail-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#formatted-text</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>italic-text</key>
		<dict>
			<key>begin</key>
			<string>(?x)               (?&lt;=^|[\s\(!]) (_{1,2}) (?=(\S|\S.*?\S)  \1    ($|[\s,\.\?!:;\)]))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.italic.begin.twiki</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Matches both _..._ and __...__ (bold) forms..</string>
			<key>end</key>
			<string>(?x) ((?=[^\1]*$)|(?&lt;=                                    \S) (\1) (?=$|[\s,\.\?!:;\)]))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.italic.end.twiki</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.italic.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Don't match nested italic text.</string>
					<key>match</key>
					<string>_</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>labelled-link</key>
		<dict>
			<key>begin</key>
			<string>(?x)(?&lt;!!)(?= \[\[ [^\]\[]* \]\[ [^\]\[]* \]\])</string>
			<key>comment</key>
			<string>A [[link][label]] link. Can be escaped with !, but not &lt;nop&gt;.</string>
			<key>end</key>
			<string>(\]\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.link.end.twiki</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.link.named.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.link.begin.twiki</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>markup.underline.link.twiki</string>
					<key>end</key>
					<string>(\]\[)(?=.*?\]\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.link.middle.twiki</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variable-reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#formatted-text</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>links</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#wikiword-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#forced-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#labelled-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inet-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mail-link</string>
				</dict>
			</array>
		</dict>
		<key>literal</key>
		<dict>
			<key>begin</key>
			<string>(?=&lt;(pre|literal)\b)</string>
			<key>comment</key>
			<string>&lt;literal&gt;...&lt;/literal&gt; and &lt;pre&gt;...&lt;/pre&gt;. Similar to &lt;verbatim&gt; except variable references and HTML is allowed.</string>
			<key>end</key>
			<string>(&lt;/)(\1)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki punctuation.definition.tag.begin.twiki</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki entity.name.tag.other.twiki</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki punctuation.definition.tag.end.twiki</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.literal.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.*?</string>
					<key>name</key>
					<string>markup.raw.twiki</string>
				</dict>
			</array>
		</dict>
		<key>mail-link</key>
		<dict>
			<key>match</key>
			<string>(?x) (?&lt;!!) (mailto:)? \w+[-.\w]*@[-a-z0-9]+(\.[-a-z0-9]+)*\.[a-z]+</string>
			<key>name</key>
			<string>markup.underline.link.mail.twiki</string>
		</dict>
		<key>meta-data</key>
		<dict>
			<key>begin</key>
			<string>^%META:[A-Z][A-Z0-9_]*{</string>
			<key>comment</key>
			<string>Like a variable reference, but: 1) can only appear at start of line, and 2) can't be nested.</string>
			<key>end</key>
			<string>}%</string>
			<key>name</key>
			<string>variable.other.meta-data.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.twiki</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.twiki</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\w+)\s*=\s*(".*?")</string>
				</dict>
			</array>
		</dict>
		<key>noautolink</key>
		<dict>
			<key>begin</key>
			<string>(?=&lt;noautolink\b)</string>
			<key>comment</key>
			<string>&lt;noautolink&gt;...&lt;/noautolink&gt;. Like top level but WikiWords are not recognised.</string>
			<key>end</key>
			<string>(&lt;/)(noautolink)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki punctuation.definition.tag.begin.twiki</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki entity.name.tag.other.twiki</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki punctuation.definition.tag.end.twiki</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.noautolink.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#top-no-wikiword</string>
				</dict>
			</array>
		</dict>
		<key>numbered-list</key>
		<dict>
			<key>begin</key>
			<string>^(?:   )+(\d+\.?|[AaIi]\.)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.numbered-list.twiki</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Multiple of 3 spaces, then either: any number of digits and an optional period, or a single 'A', 'a', 'I' or 'i' and a required period.</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.list.numbered.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>raw-text</key>
		<dict>
			<key>begin</key>
			<string>(?x)               (?&lt;=^|[\s\(!]) (={1,2}) (?=(\S|\S.*?\S)  \1    ($|[\s,\.\?!:;\)]))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.twiki</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Matches both =...= and ==...== (bold) forms.</string>
			<key>end</key>
			<string>(?x) ((?=[^\1]*$)|(?&lt;=                                    \S) (\1) (?=$|[\s,\.\?!:;\)]))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.twiki</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Don't match nested raw text.</string>
					<key>match</key>
					<string>=</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>separator</key>
		<dict>
			<key>comment</key>
			<string>3 or more dashes. Non-dash characters (including white space) are not permitted before or after the dashes.</string>
			<key>match</key>
			<string>^---+$</string>
			<key>name</key>
			<string>keyword.other.separator.twiki</string>
		</dict>
		<key>skin-template-comment</key>
		<dict>
			<key>begin</key>
			<string>%{</string>
			<key>end</key>
			<string>}%</string>
			<key>name</key>
			<string>comment.block.skin-template.twiki</string>
		</dict>
		<key>skin-template-directive</key>
		<dict>
			<key>comment</key>
			<string>Skin templates are a feature of Foswiki, for more info see http://foswiki.org/220tem/SkinTemplates. Limitations: 1) Should recognise template paramters within a DEF/END section, 2) Comments should only be recognised within a DEF/END section.</string>
			<key>match</key>
			<string>%TMPL:(END|PREV)%</string>
			<key>name</key>
			<string>variable.other.skin-template.twiki</string>
		</dict>
		<key>skin-template-directive-with-params</key>
		<dict>
			<key>begin</key>
			<string>%TMPL:(DEF|INCLUDE|P){</string>
			<key>end</key>
			<string>}%</string>
			<key>name</key>
			<string>variable.other.skin-template.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.twiki</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.twiki</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\w+)\s*=\s*(".*?")</string>
				</dict>
				<dict>
					<key>match</key>
					<string>".*?"</string>
					<key>name</key>
					<string>string.quoted.double.twiki</string>
				</dict>
			</array>
		</dict>
		<key>table-row</key>
		<dict>
			<key>begin</key>
			<string>(?x)  ^\s*(\|)  (?=.*(\|\s*|\\)$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.table-row.begin.twiki</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Table row line must begin with a '|' and finish with a '|' or a backslash (line continuation). Whitespace before and after '|' is ignored.</string>
			<key>end</key>
			<string>(\|)\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.table-row.end.twiki</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tablerow.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.table-row.middle.twiki</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\|)(?!\s*$)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.table-row.continuation.twiki</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\)$</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Row terminated without | or backslash is invalid. Weirdness: need to explicitly match newline at the end, otherwise, the newline after a line ending in gets matched by this rule; I don't understand it.</string>
					<key>match</key>
					<string>[^\|\\]\s*
$</string>
					<key>name</key>
					<string>invalid.illegal.table-row.twiki</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.table-row.cell-extend.twiki</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\|)\s*(\^)\s*(?=\|)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>top-no-wikiword</key>
		<dict>
			<key>comment</key>
			<string>Top level pattern (excluding wiki word links).</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#verbatim</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heading</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-no-wikiword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bulleted-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbered-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#definition-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#anchor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#table-row</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#skin-template-directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#skin-template-directive-with-params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#skin-template-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta-data</string>
				</dict>
			</array>
		</dict>
		<key>variable-definition</key>
		<dict>
			<key>begin</key>
			<string>^(?:   )+(\* (?:Set|Local)) ([A-Z][A-Z0-9_]*) (=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.vardef.twiki</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.twiki</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.vardef.twiki</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>[multiple of 3 sp] * [sp] Set|Local [sp] NAME [sp] = [sp] value. Variable name must be all capitals, may have digits and underscores, but can't start with a digit.</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.variable-definition.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>variable-param-value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-reference</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.*?</string>
					<key>name</key>
					<string>string.quoted.double.twiki</string>
				</dict>
			</array>
		</dict>
		<key>variable-reference</key>
		<dict>
			<key>comment</key>
			<string>Uppercase letters only (no digits at start), no white space, '!' prefix escapes it.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-reference-no-params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-reference-with-params</string>
				</dict>
			</array>
		</dict>
		<key>variable-reference-no-params</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable-reference.begin.twiki</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable-reference.end.twiki</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;!!)(%)[A-Z][A-Z0-9_]*(%)</string>
			<key>name</key>
			<string>variable.other.twiki</string>
		</dict>
		<key>variable-reference-with-params</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!!)(%)[A-Z][A-Z0-9_]*({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable-reference.twiki</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable-reference.twiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(}%)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable-reference.twiki</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.variable-reference.twiki variable.other.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\w+\s*)=\s*(")(?=.*")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.twiki</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.twiki</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Parameter name/value pair.</string>
					<key>end</key>
					<string>(")|(?=}%)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.twiki</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variable-param-value</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>("|')(?=.*\1)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.twiki</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Parameter value only; no name.</string>
					<key>end</key>
					<string>(\1)|(?=}%)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.twiki</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variable-param-value</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-param-value</string>
				</dict>
			</array>
		</dict>
		<key>verbatim</key>
		<dict>
			<key>begin</key>
			<string>(&lt;)(verbatim)(\s*([^&gt;\s]+)\s*=\s*([^&gt;\s]+)\s*)?[^&gt;]*(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki punctuation.definition.tag.begin.twiki</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki entity.name.tag.other.twiki</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki entity.other.attribute-name.twiki</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki string.quoted.double.twiki</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki punctuation.definition.tag.end.twiki</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Can not contain TWiki markup or HTML. No space permitted within &lt;verbatim or &lt;/verbatim part of tags. Can contain variable definitions. Limitations: 1) Very rudimentary attributes matching, and 2) &lt;verbatim&gt; Tags must be defined on a single line.</string>
			<key>contentName</key>
			<string>markup.raw.twiki</string>
			<key>end</key>
			<string>(&lt;/)(verbatim)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki punctuation.definition.tag.begin.twiki</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki entity.name.tag.other.twiki</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.twiki punctuation.definition.tag.end.twiki</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.verbatim.twiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-definition</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;)(verbatim)([^&gt;]*)(&gt;)</string>
					<key>comment</key>
					<string>Nested &lt;verbatim&gt; tags.</string>
					<key>end</key>
					<string>(&lt;/)(verbatim)\s*(&gt;)</string>
					<key>name</key>
					<string>markup.raw.twiki</string>
				</dict>
			</array>
		</dict>
		<key>wikiword-link</key>
		<dict>
			<key>comment</key>
			<string>Wikiword link is formed when there is 2 or more words with initial capitals, run together. A Wiki web name must start with a capital, and followed by nothing or alphanumeric text. A &lt;nop&gt; and ! prefix is used to escape a Wiki word.</string>
			<key>match</key>
			<string>(?x)  (?&lt;![!%]|&lt;nop&gt;) \b ((?:[A-Z]\w*\.)+|(?&lt;!\.)) ((?:[A-Z][a-z]+[A-Z])[A-Za-z0-9]*) \b</string>
			<key>name</key>
			<string>markup.underline.link.twiki</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.twiki</string>
	<key>uuid</key>
	<string>b4fd8dab-fc80-4fdb-864f-77edfd4f09ad</string>
</dict>
</plist>
